apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
     containers:
      - name: moderation
        image: hadiahmed2002/moderation
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-cip-srv
spec:
  selector:
    app: moderation
  type: ClusterIP
  ports: 
    - name: moderation
      protocol: TCP
      port: 4002
      targetPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-np-srv
spec:
  type: NodePort
  selector:
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 4002
      targetPort: 4002
