apiVersion: apps/v1
kind: Deployment
metadata:
  name: queryservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queryservice
  template:
    metadata:
      labels:
        app: queryservice
    spec:
     containers:
      - name: queryservice
        image: hadiahmed2002/queryservice
---
apiVersion: v1
kind: Service
metadata:
  name: queryservice-cip-srv
spec:
  selector:
    app: queryservice
  type: ClusterIP
  ports: 
    - name: queryservice
      protocol: TCP
      port: 4003
      targetPort: 4003
---
apiVersion: v1
kind: Service
metadata:
  name: queryservice-np-srv
spec:
  type: NodePort
  selector:
    app: queryservice
  ports:
    - name: queryservice
      protocol: TCP
      port: 4003
      targetPort: 4003
